server:
  port: 8090
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(XY8yZTMmye7QjU6j0pzrrbUGJQnx8FfxRTISOKG36a4xbq9JiaCGU5qWLSQeOpHO89xn8+eXaad5/C2LhHpqjPvjKcfjbh05pmW0+IVxxHYRJgMXCjflJQ==)
    username: ENC(wHVzLrcm3E13azGi9I/Kag==)
    password: ENC(s3e3oTYr2hNWoTNEpM/m32SlSNW+7jCi)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

app:
  auth:
    tokenSecret: wdw_server_jjang
    tokenExpirationMsec: 864000000
#    (1000) * (60) * (60) * (24) * (365)