server:
  port: 8090
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(XY8yZTMmye7QjU6j0pzrrbUGJQnx8FfxRTISOKG36a4xbq9JiaCGU5qWLSQeOpHO89xn8+eXaad5/C2LhHpqjPvjKcfjbh05pmW0+IVxxHYRJgMXCjflJQ==)
    username: ENC(wHVzLrcm3E13azGi9I/Kag==)
    password: ENC(s3e3oTYr2hNWoTNEpM/m32SlSNW+7jCi)
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(5DNOrIWNCVK5ulAsMwGbzTeZUhOL/yNu9yPOmHVZPv6E3VwDsuIg/JF7JxQUSs7LIMyRjvBb4jBJ6ntTMsplj90Npa7V1R/ptqW909g3auRk2tRqiYXlBA==)
            client-secret: ENC(vsa0d4IfBmEoIf7Ig5PfABfcnl+fXCfXtTb6Zym2IYQm9VPm5nfUTMLESBWugwFx)
            scope:
              - email
              - profile

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

app:
  auth:
    tokenSecret: wdw_server_jjang
    tokenExpirationMsec: 864000000
#    (1000) * (60) * (60) * (24) * (365)