server:
  port: 8090
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(XY8yZTMmye7QjU6j0pzrrbUGJQnx8FfxRTISOKG36a4xbq9JiaCGU5qWLSQeOpHO89xn8+eXaad5/C2LhHpqjPvjKcfjbh05pmW0+IVxxHYRJgMXCjflJQ==)
    username: ENC(wHVzLrcm3E13azGi9I/Kag==)
    password: ENC(s3e3oTYr2hNWoTNEpM/m32SlSNW+7jCi)
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(5DNOrIWNCVK5ulAsMwGbzTeZUhOL/yNu9yPOmHVZPv6E3VwDsuIg/JF7JxQUSs7LIMyRjvBb4jBJ6ntTMsplj90Npa7V1R/ptqW909g3auRk2tRqiYXlBA==)
            client-secret: ENC(vsa0d4IfBmEoIf7Ig5PfABfcnl+fXCfXtTb6Zym2IYQm9VPm5nfUTMLESBWugwFx)
            scope:
              - email
              - profile
          kakao:
            authorization-grant-type: authorization_code
            client-id: ENC(AXBpFlskZLMNMt/5hGTxDr6urbIzXzJaH5o63Mk+s3QPVNLPpVlt2sNoYKeSZUbl)
            client-secret: ENC(rTYfQXFnSbl2+gf2SkU7hhGhtS6XrMpOD59+WFGEYRh+5SjMK/bCTfcMyerQFmbX)
            redirect-uri: "http://localhost:8090/login/oauth2/code/kakao"
            scope:
              - profile_nickname
              - account_email
            client-authentication-method: POST
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: ${JASYPT_ENCRYPTOR_PASSWORD}

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

app:
  auth:
    tokenSecret: ENC(h2IaKMdf9a/ovb6Yz7hGymDglXrbmh0Wpofbv8Xhyhc=)
    tokenExpirationMsec: 864000000
#    (1000) * (60) * (60) * (24) * (365)