server:
  port: 8090
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://wdw-server.cwas4ywuxhjs.ap-northeast-2.rds.amazonaws.com/wdw
    username: master
    password: wdw1234!

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

app:
  auth:
    tokenSecret: wdw_server_jjang
    tokenExpirationMsec: 864000000
#    (1000) * (60) * (60) * (24) * (365)