spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: wdw-server.cwas4ywuxhjs.ap-northeast-2.rds.amazonaws.com:3306/wdw?serverTimezone=Asia/Seoul
    username: master
    password: wdw1234!

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace